# name of the software
name: ftjahn8's GoldTool

remote_theme: allejo/jekyll-docs-theme@v1.0.0

project:
  version: 1.0.0
  download_url: https://github.com/ftjahn8/WOT-GoldTool/releases
  download_text: Download

license:
  software: GNU GPL v3.0
  software_url: https://opensource.org/licenses/GPL-3.0

  docs: CC BY 3.0
  docs_url: https://creativecommons.org/licenses/by/3.0/

links:
  header:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/ftjahn8/WOT-GoldTool
  homepage:
    - title: View on GitHub
      icon: github
      brand: true
      url: https://github.com/ftjahn8/WOT-GoldTool
  footer:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/ftjahn8/WOT-GoldTool
    - title: Issues
      icon: bug
      url: https://github.com/ftjahn8/WOT-GoldTool/issues?state=open

ui:
  mode: 'dark'
  brand:
    dark: "#00ceff"
    light: "#a20000"
  border_color:
    dark: "#5f5f5f"
    light: "#dee2e6"
  header:
    trianglify: true
    dark:
      color1: "#062a48"
      color2: "#304e67"
    light:
      color1: "#080331"
      color2: "#673051"
  masthead:
    color:
      dark: "#fff"
      light: "#fff"
    align:
      homepage: 'center'
      page: 'left'
